/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "By controlling the money supply, the Reserve can influence the economy to benefit whichever politician it chooses.": "通过控制货币供应量，储备可以影响经济，使其选择的任何政治家受益。",
    "Children are easily tricked into working for free. Put them to work selling lemon-flavored sugar water.": "孩子们很容易被骗去免费工作。让他们去卖柠檬味的糖水。",
    "Click Sector Icon": "单击扇区图标",
    "Clicker": "点击器",
    "Combine greed, lack of moral compass, and a hefty dose of blackmail and you've got yourself control of the Presidency.": "结合贪婪、缺乏道德指南针和大量勒索，你已经控制了总统职位。",
    "Combining viral memes together to create the dankest masterpieces.": "将病毒模因结合在一起，创造出最性感的杰作。",
    "Congratulations, our conspiracy has dominated the world!": "恭喜，我们的阴谋统治了世界！",
    "Conspiracy": "阴谋",
    "Constant campaigning means they have little time for writing laws, but the one's they do write are completely self-serving.": "持续的竞选活动意味着他们几乎没有时间编写法律，但他们所写的法律完全是自私自利的。",
    "Continue...": "继续...",
    "Cookie Clicker": "饼干点击器",
    "Covert Trading Council": "秘密交易委员会",
    "Crooked Congressmen": "歪歪扭扭的国会议员",
    "Currencies can be transferred between sectors\n\t\t\t\t\tby activating one of the arrows/buttons connecting the three sector icons.\n\t\t\t\t\tOnly one transfer can be active at a time. Financing and contributions move money, \n\t\t\t\t\ttax breaks turn votes into money, propaganda turns mind control into votes,\n\t\t\t\t\tand ads turn mind control into money for industry. Campaigns use money to create\n\t\t\t\t\tvotes, while a mass broadcast will convert money into mind control.\t\n": "可以在扇区之间转移货币\n\t\t\t\t\t通过激活连接三个扇区图标的箭头/按钮之一。\n\t\t\t\t\t一次只能激活一次转移时间。筹资和捐款转移金钱，\n\t\t\t\t\t税收减免将选票变为金钱，宣传将精神控制变为选票，\n\t\t\t\t\t 广告将精神控制变为金钱行业。竞选活动使用金钱来创造\n\t\t\t\t\tvotes，而大规模广播将金钱转化为精神控制。\t\n",
    "Cutthroat Reality Shows": "残酷的真人秀",
    "Dangerous Deregulation": "危险的放松管制",
    "Dank Memes": "谢谢表情包",
    "Dark Skies Lobbying Group": "黑暗天空游说团体",
    "Deathray Games": "死亡射线游戏",
    "Delete Saved Game": "删除已保存的游戏",
    "Delete Saved Game and Restart": "删除保存的游戏并重新启动",
    "Ducttape Healthcare": "管道胶带医疗保健",
    "Each sector has it's own funds and it's own specialty. \n\t\t\tIndustry's primarily job is generating money; Politics can generate votes or money;\n\t\t\tMedia can generate controlled minds or money.": "每个部门都有自己的资金和自己的专长。 \n\t\t\t行业的主要工作是赚钱；政治可以产生选票或金钱；\n\t\t\t媒体可以产生受控制的思想或金钱。",
    "Elder Bank": "长者银行",
    "Election Attack Ads": "选举攻击广告",
    "Every click will generate money. The \n\t\t\t\t\tmore upgrades you have, the more money you'll generate with each click.\n": "每一次点击都会产生金钱。 \n\t\t\t\t\t您拥有的升级越多，每次点击产生的钱就越多。\n",
    "EyeTube": "眼管",
    "Food so large you'll be forever full and bloated.": "食物这么大，你会永远吃饱和臃肿。",
    "Foxy 21 News": "狡猾的 21 新闻",
    "Fraternity brothers help raise money and get the vote out.": "兄弟会兄弟帮助筹集资金并获得投票。",
    "Freebuilders Guild": "自由建设者公会",
    "Funneling factory-produced blonde bigots into TV studios provides entertainment news for the masses.": "将工厂生产的金发偏执者汇集到电视演播室为大众提供娱乐新闻。",
    "GMO Super-Sloth Super-Food": "转基因超级懒惰超级食物",
    "HapChem Pharmaceuticals": "HapChem 制药",
    "Happy life is happy. Happy time. Take your pill. Happy.": "幸福的生活是幸福的。欢乐时光。吃药。快乐的。",
    "Happy Rat Conglomerate": "快乐鼠集团",
    "Hollywood Films": "好莱坞电影",
    "How would politicians know what vote for unless they are told by the titans of industry in shadowy back-room meetings?": "政客们怎么会知道投票的结果，除非他们在阴暗的幕后会议上被行业巨头告知？",
    "If we fixed the underlying problem we would lose all our customers. Free bankruptcy support after each visit.": "如果我们解决了根本问题，我们将失去所有客户。每次访问后免费提供破产支持。",
    "In order for our organization to dominate the world, we will need a vast conspiracy\n\t\t\tto draw together various sources of power.": "为了让我们的组织统治世界，我们需要一个巨大的阴谋\n\t\t\t来汇集各种力量来源。",
    "In order to accomplish this we will need a lot of money, so it's vital that\n\t\t\twe control the": "为了实现这一点，我们需要大量资金，因此\n\t\t\twe 控制",
    "Industry": "工业",
    "Instructions": "指示",
    "International Reserve": "国际储备",
    "Internet Censorship": "互联网审查",
    "Irresponsible Deregulation": "不负责任的放松管制",
    "It is time that our organization fulfills the ancient prophecies \n\t\t\tand creates a New World Order!": "现在是我们组织实现古老预言\n\t\t\t 并创建新世界秩序的时候了！",
    "Keep Playing": "继续玩",
    "Last saved": "最后保存",
    "League of Governors": "州长联盟",
    "Lemonade Sweatshop": "柠檬水血汗工厂",
    "Load Saved Game": "加载保存的游戏",
    "Local Corrupt Politicians": "地方腐败政客",
    "Ludum Dare": "鲁杜姆敢",
    "Makers of Apex-Predator drones that excel at killing other drones.": "擅长杀死其他无人机的 Apex-Predator 无人机制造商。",
    "Media": "媒体",
    "media $ -->> minds": "媒体 $ -->> 思想",
    "media $ <<-- ind. $": "媒体 $ <<-- 工业。 $",
    "Media Shell Corporation": "媒体壳公司",
    "Megalomaniac Mayors": "狂妄自大的市长",
    "Megaton Mining": "百万吨矿业",
    "Menu": "菜单",
    "minds -->> ind. $": "思想 -->> 工业。 $",
    "Minds Controlled": "思想控制",
    "minds/sec": "思想/秒",
    "Much of our power will come about by convincing the people \n\t\t\tof the planet that our ways are best. \n\t\t\tTo do this we will need to utilize\n\t\t\tthe": "我们的大部分力量将通过让地球上的人们\n\t\t\t相信我们的方式是最好的而产生。 \n\t\t\t为此，我们需要利用\n\t\t\tthe",
    "Mutually Assured Domination -- the threat of nuclear destruction will help to unite the world in fear.": "相互保证的统治——核毁灭的威胁将有助于在恐惧中团结世界。",
    "National Demopublican Party": "全国民主党",
    "National Republicrat Party": "全国共和党",
    "New World Order": "新世界秩序",
    "Newsstands": "报摊",
    "No need to watch long ads when they can just be flashed right into your unconscious mind. 'BUY BUY BUY'": "当它们可以直接闪入您的潜意识时，无需观看长广告。 '买买买'",
    "No, they don't produce lightcycles, but they do manage most of the world's electricity.": "不，它们不生产光循环，但它们确实管理着世界上大部分的电力。",
    "of the world. With the profits of all\n\t\t\tthe businesses combined together, everything we need will be for sale.\n\t\t\tFortunately the political realm and the media are already easily subjugated \n\t\t\tby money; if we are patient with our conspiratorial schemes, we cannot fail.": "世界的。所有企业的利润\n\t\t\t加在一起，我们需要的一切都将被出售。\n\t\t\t幸运的是，政治领域和媒体已经很容易被征服\n\t\t\用钱；如果我们对我们的阴谋计划有耐心，我们就不会失败。",
    "Ok, I got it.": "好，我知道了。",
    "Once you have enough money, buy an upgrade by clicking the button. Upgrades automatically generate money, gather votes, or control minds.": "一旦你有足够的钱，点击按钮购买升级。升级会自动产生金钱、收集选票或控制思想。",
    "One of these fine people will become president, and it won't matter who as long as we control them all.": "这些优秀的人中的一个将成为总统，只要我们控制他们，谁都不重要。",
    "or the": "或者",
    "Original mini-LD version": "原始迷你LD版本",
    "Owning a media corporation makes sure that pesky issues like worker rights and pollution never become news stories.": "拥有一家媒体公司可以确保工人权利和污染等令人讨厌的问题永远不会成为新闻报道。",
    "Pantheon Drone Defense Corp.": "万神殿无人机防御公司",
    "Plug your brain in to a constant stream of political rants and pet photos.": "将您的大脑投入到源源不断的政治咆哮和宠物照片中。",
    "pol. $ -->> votes": "政治 $ -->> 投票",
    "Politcal Dynasty": "政治王朝",
    "Politics": "政治",
    "Prepare the bombs, it is time to delve too greedily and too deep!": "准备好炸弹，是时候钻得太贪心太深了！",
    "Presidential Candidates": "总统候选人",
    "Pro-Big-business news articles from around the globe.": "来自全球的亲大企业新闻文章。",
    "Profit": "利润",
    "Profit: \n\t": "利润：\n\t",
    "Progress controlling minds & votes": "进度控制思想和选票",
    "Progress unlocking upgrades": "进度解锁升级",
    "Puppet President": "傀儡总统",
    "Purchase Upgrades": "购买升级",
    "Quik-e-Gunz 'n' Beer": "快枪手 'n' 啤酒",
    "Radio shows so loud and angry at the world, that they are audible across the country.": "广播节目对世界如此响亮和愤怒，以至于在全国都能听到。",
    "Remind the public of every bad thing that anyone has suggested about your opponents.": "提醒公众任何人对你的对手提出的每件坏事。",
    "Removing regulation on key businesses helps profits to soar!": "取消对重点业务的监管有助于利润飙升！",
    "Return to Game": "返回游戏",
    "Review Intro": "回顾介绍",
    "Review Tips": "查看提示",
    "Robo-Dialer": "机器人拨号器",
    "Robo-Dialer can't be reasoned with; it doesn't feel pity, or remorse, or fear; and it absolutely will not stop.": "Robo-Dialer 无法推理；它不会感到怜悯、悔恨或恐惧；它绝对不会停止。",
    "Rockefelberg News": "洛克菲堡新闻",
    "Rogue Blogger Network": "流氓博客网络",
    "Save Game Now": "立即保存游戏",
    "seconds ago": "几秒钟前",
    "Secret Mistresses": "秘密情妇",
    "Seductive Interns": "诱人的实习生",
    "Seductive interns are excellent are raising funds and raising spirits. Expenses include cigars and dry-cleaning.": "诱人的实习生在筹集资金和提高精神方面非常出色。费用包括雪茄和干洗。",
    "Shark Law Firm": "鲨鱼律师事务所",
    "Sinister Senators": "险恶的参议员",
    "Sludge Family Oil": "污泥家庭油",
    "So Beyond Top Secret .net": "所以超越绝密.net",
    "Some are young, some are old, but they all hate people who look and speak different.": "有些人年轻，有些人老了，但他们都讨厌长相和说话不同的人。",
    "Spam written by former Nigerian princes posing as sexy rebels who know the 'truth' about the government.": "由前尼日利亚王子撰写的垃圾邮件，他们伪装成了解政府“真相”的性感叛军。",
    "Subliminal Advertising": "潜意识广告",
    "Subversive Spam": "颠覆性垃圾邮件",
    "Super PAC": "超级PAC",
    "Targeting the few remaining people that still get their news from writing printed on dead trees.": "针对仅存的少数仍然通过在死树上印刷的文字获得新闻的人。",
    "Tear away the old order and replace it with your conspiracy's new, global order.": "撕掉旧秩序，用你的阴谋的全球新秩序取而代之。",
    "Terran Petroleum": "人族石油",
    "The ability to instantly discredit oppositional news agencies as 'fake news' helps to win votes and provide profits to friendly news media.": "立即将反对派新闻机构抹黑为“假新闻”的能力有助于赢得选票并为友好的新闻媒体提供利润。",
    "The company founded on a cartoon of a dancing rat slowly controls every entertainment I.P. imaginable.": "该公司以一只跳舞的老鼠卡通为基础，慢慢控制着每一个娱乐IP。可以想象。",
    "The Freebuilders are a secret society based on Minecraft masonry. Block by block they have dominated international politics.": "Freebuilders 是一个以 Minecraft 砖石为基础的秘密社团。他们一个接一个地主导着国际政治。",
    "The governors gather monthly in a giant, dark, helmet-shaped fortress in a shady swamp.": "州长们每月聚集在一个巨大的、黑暗的、头盔状的堡垒中，位于阴凉的沼泽中。",
    "The Grid": "网格",
    "the Illuminati card game": "光明会纸牌游戏",
    "The network is everywhere, in all devices, constantly watching you and displaying creepily relevant ads.": "网络无处不在，在所有设备中，不断地监视您并显示令人毛骨悚然的相关广告。",
    "These are listed below each sector icon; \n\t\t\t\t\tclick the button to purchase one upgrade (if you have the funds), or click the\n\t\t\t\t\tupgrade to see more details. Some upgrades in a sector will aid another sector.\n": "这些列在每个扇区图标下方； \n\t\t\t\t\t单击按钮购买一次升级（如果您有资金），或单击\n\t\t\t\t\t升级查看更多详细信息。一个扇区的一些升级将有助于另一个扇区。\n",
    "These loose women help to bring scandal to opponents and dominate news stories.": "这些松散的女性有助于给对手带来丑闻并主导新闻报道。",
    "These must-have phones and gadgets are only made in the world's top bananana republics": "这些必备手机和小工具仅在世界顶级香蕉共和国制造",
    "These political action committees pour money into politics, shaping all the public debates.": "这些政治行动委员会将资金投入政治，塑造了所有的公共辩论。",
    "These politicians focus entirely on consolidating political power.": "这些政客完全专注于巩固政治权力。",
    "These small shops sell everything you might need to keep you satiated, intoxicated, and dangerous.": "这些小商店出售您可能需要的一切，让您保持饱足、陶醉和危险。",
    "These ugly men promote themselves as much as they promote the latest conspiracy theories.": "这些丑陋的男人在宣传最新的阴谋论时宣传自己。",
    "They love the smell of blood, almost as much as the smell of money.": "他们喜欢血腥味，几乎和金钱味一样。",
    "They make sure that the Earth is robbed of all it's resources, sometimes spilling oil on purpose if it can't be sold fast enough.": "他们确保地球的所有资源都被抢走，如果不能足够快地出售石油，有时会故意泄漏石油。",
    "They won't get anything notable accomplished, but they'll make people think democracy works.": "他们不会取得任何显着的成就，但他们会让人们认为民主有效。",
    "This bank has controlled the financial sector since the dawn of civilization, and will continue forever.": "这家银行自文明之初就控制了金融部门，并将永远持续下去。",
    "This conglomerate controls news media and movies, but mainly focuses on nude photos of celebrities and politicians.": "该集团控制新闻媒体和电影，但主要关注名人和政客的裸照。",
    "This game is made up of three different sectors - Industry, Politics, Media - \n\t\t\tand three different currencies: money, votes, and controlled minds.": "该游戏由三个不同的部门组成 - 工业、政治、媒体 - \n\t\t\t 和三种不同的货币：金钱、选票和受控制的思想。",
    "This government-sanctioned council meets in secret to shift funds to wherever they are needed.": "这个政府批准的委员会秘密开会，将资金转移到需要的地方。",
    "This loose alliance of mayors is mostly fueled by drug binges.": "这种松散的市长联盟主要是由吸毒引起的。",
    "This MMO game allows citizen to mindless grind in a virtual world while spy agencies observe every detail.": "这款 MMO 游戏允许公民在虚拟世界中无意识地磨练，而间谍机构则观察每一个细节。",
    "This shadowy, private conference of the industrial, business, and political elite is also the owner of a fast food chain.": "这个由工业、商业和政治精英组成的隐秘私人会议也是快餐连锁店的所有者。",
    "This unassuming patch of grass is also a secret meetingplace for the world's elite powerbrokers.": "这片不起眼的草地也是世界精英权力掮客的秘密聚会场所。",
    "Time-Weiner Media Group": "时代威纳传媒集团",
    "to educate the willing and brainwash the rest of the\n\t\t\tpopulation.": "教育有意愿的人和洗脑其余的\n\t\t\t人口。",
    "To play this game you will utilize three main features: Clicking, Buying upgrades, and Transfers.\n\t\t\tClick one of the sector icons to generate money.": "要玩这个游戏，您将利用三个主要功能：点击、购买升级和转移。\n\t\t\t点击一个部门图标来赚钱。",
    "To win you will need to unlock all upgrades and get billions of votes and minds.\n\t\t\tYour progress will be shown on this bar. \n\t\t\tGood luck taking over the world!": "要赢得胜利，您需要解锁所有升级并获得数十亿的选票和思想。\n\t\t\t您的进度将显示在此栏上。 \n\t\t\t祝你好运接管世界！",
    "Toggle Sound": "切换声音",
    "Towing Garages": "拖车场",
    "Transfers": "转移",
    "Try transferring money between sectors, or transferring money to votes or minds.": "尝试在部门之间转移资金，或将资金转移到选票或思想中。",
    "Ultra GameBox MK": "Ultra GameBox MK",
    "Video games so high-def and well simulated that they feel like hallucinations. Or is it the other way around?": "视频游戏如此高清且模拟效果如此之好，以至于它们感觉就像是幻觉。或者是周围的其他方式？",
    "Violence, sex, and comic book characters are three things that never get old and always turns a profit.": "暴力、性和漫画人物是三样东西，永远不会变老，总是会盈利。",
    "Votes": "投票",
    "votes -->> media $": "投票 -->> 媒体 $",
    "votes <<-- minds": "投票<<--思想",
    "votes/sec": "票数/秒",
    "We agree with everything our opponents stand for! Paid for by the campaign to elect John Jackson.": "我们同意我们的对手所代表的一切！由选举约翰·杰克逊的竞选活动支付。",
    "We are against those things that everyone hates! Paid for by the campaign to elect Jack Johnson.": "我们反对那些每个人都讨厌的东西！由选举杰克约翰逊的竞选活动支付。",
    "We don't really care where you were parked. If you want your car back, you can either pay us or climb the razor-wire fence.": "我们真的不在乎你停在哪里。如果您想取回您的车，您可以付钱给我们或爬上铁丝网。",
    "We still found some more regulations to remove. Every man for themselves!": "我们仍然发现了一些需要删除的规定。每个男人都为自己！",
    "We will also need to need to co-opt the democractic process and ensure that\n\t\t\twe have full control over all": "我们还需要选择民主进程，并确保\n\t\t\twe 完全控制所有",
    "While you watch the miriad of videos, EyeTube watches back.": "当您观看大量视频时，EyeTube 会回看。",
    "Who knows - maybe one of these stars can become the next puppet president!": "谁知道——说不定这些明星中的一个可以成为下一任傀儡总统！",
    "Who needs boring 'Net Neutrality', when we can have exciting Net Lawful-Evilness? Control of all rival information is cut off.": "当我们可以拥有令人兴奋的网络合法邪恶时，谁需要无聊的“网络中立”？对所有竞争对手信息的控制被切断。",
    "Why let someone new run for office when you can have Dear Leader's relative? No need to learn a new last name.": "既然可以有亲爱的领导的亲戚，为什么还要让新人竞选公职？无需学习新的姓氏。",
    "World of Spycraft": "间谍世界",
    "Xenophobic TV Hosts": "排外电视主持人",
    "Blowhard Radio Show": "吹牛大王电台节目",
    "Bohemian Field": "波西米亚球场",
    "BrainBook": "脑书",
    "Build-a-Burger Group": "建立一个汉堡集团",
    "Buy": "买",
    "campaign": "活动",
    "contribution": "贡献",
    "Donations": "捐款",
    "finance": "金融",
    "ind. $ -->> pol. $": "工业 $ -->> 政治 $",
    "ind. $ <<-- votes": "工业 $ <<-- 投票",
    "Influence": "影响",
    "mass broadcast": "大众广播",
    "Profit: ": "利润：",
    "propaganda": "宣传",
    "Reach": "抵达",
    "tax break": "减税",
    ". Once our politicians\n\t\t\tare enstated, they will control the agenda and the voters will flock to them.": ". 一旦我们的政客\n\t\t\被任命，他们将控制议程，选民将蜂拥而至。",
    "'Shore to Shore' Radio": "“岸对岸”电台",
    "'Wait... this whole time we could have just printed complete lies? This changes everything.'": "'等等......这整个时间我们都可以打印完整的谎言？ 这改变了一切。",
    "\"Classic\" version (1.0": "“经典”版本（1.0",
    "\"Fake News\"": "“假新闻”",
    "A marriage between a Texan political family and a middle east oil family produced a massive oil tycoon dynasty.": "一个德克萨斯政治家族和一个中东石油家族的联姻产生了一个庞大的石油大亨王朝。",
    "About": "关于",
    "ads": "广告",
    "Alpha Sigma Sigma": "阿尔法西格玛",
    "Alternative Facts": "替代事实",
    "Bananana Gadgets": "香蕉小工具",
    "$/click": "$/点击",
    "$/sec": "$/秒",
    "": "",
    "Version": "版本",
    "All code and graphics is original and copyrighted \n\t\t\t\t(or used by license, as with jQuery and Google Fonts).\n\t\t\t\tThe code is released on GitHub; please feel free to dissect it for learning purposes.\n\t\t\t\tFuther information available at \n": "所有代码和图形均为原创且受版权保护 \n\t\t\t\t（或通过许可使用，如 jQuery 和 Google 字体）。\n\t\t\t\t代码在 GitHub 上发布；请随时剖析它以供学习。\n\t\t\t\t更多信息可在 \n",
    "and": "和",
    "Conspiracy Clicker was originally designed and created by Luke Nickerson in \n\t\t\t\t48 hours for mini-LD #48 in Jan 2014. Additional creative input by Jeffery M. Beach.": "阴谋点击器 最初是由 Luke Nickerson 在 \n\t\t\t\t48 小时内为 mini-LD #48 于 2014 年 1 月设计和创建的。Jeffery M. Beach 的额外创意输入。",
    "If you'd like to try out older versions you can play the \n": "如果你想尝试旧版本，你可以玩\n",
    "In order to win, you need to have billions of voters and minds \n\t\t\t\tsecure under your control. your progress can be measured with the progress bar at\n\t\t\t\tthe top.": "为了赢得胜利，你需要有数十亿的选民和思想在你的控制之下\n\t\t\t\t安全。您可以使用顶部的进度条来衡量您的进度。\n\t\t\t\t。",
    "Inspired by": "灵感来自",
    "This game is made up of three different sectors - Industry, Politics, Media - \n\t\t\t\tand three different currencies: money, votes, and controlled minds.\n\t\t\t\tEach sector has it's own funds and it's own specialty. \n\t\t\t\tIndustry's primarily job is generating money; Politics can generate votes or money;\n\t\t\t\tMedia can generate controlled minds or money.": "这个游戏由三个不同的部门组成 - 工业、政治、媒体 - \n\t\t\t\t 以及三种不同的货币：金钱、选票和受控思想。\n\t\t\t\t每个部门都有它是自有资金和它自己的专长。 \n\t\t\t\t行业的主要工作是赚钱；政治可以产生选票或金钱；\n\t\t\t\t媒体可以产生受控制的思想或金钱。",
    "To play this game, you will utilize three main features:": "要玩这个游戏，您将利用三个主要功能：",
    "- Currencies can be transferred between sectors\n\t\t\t\t\tby activating one of the arrows/buttons connecting the three sector icons.\n\t\t\t\t\tOnly one transfer can be active at a time. Financing and contributions move money, \n\t\t\t\t\ttax breaks turn votes into money, propaganda turns mind control into votes,\n\t\t\t\t\tand ads turn mind control into money for industry. Campaigns use money to create\n\t\t\t\t\tvotes, while a mass broadcast will convert money into mind control.": "- 货币可以在扇区之间转移\n\t\t\t\t\t通过激活连接三个扇区图标的箭头/按钮之一。\n\t\t\t\t\t在 一次。 融资和捐款会转移金钱，\n\t\t\t\t\t税收减免将选票变为金钱，宣传将精神控制变为选票，\n\t\t\t\t\t 广告将精神控制变为金钱 行业。 竞选活动使用金钱来创造\n\t\t\t\t\tvotes，而大规模广播将金钱转化为精神控制。",
    "- Every click will generate money. The \n\t\t\t\t\tmore upgrades you have, the more money you'll generate with each click.\n": "- 每次点击都会产生金钱。 \n\t\t\t\t\t您拥有的升级越多，每次点击产生的钱就越多。\n",
    "- These are listed below each sector icon; \n\t\t\t\t\tclick the button to purchase one upgrade (if you have the funds), or click the\n\t\t\t\t\tupgrade to see more details. Some upgrades in a sector will aid another sector.\n": "- 这些列在每个扇区图标下方； \n\t\t\t\t\t单击按钮购买一次升级（如果您有资金），或单击\n\t\t\t\t\t升级查看更多详细信息。 一个扇区的一些升级将有助于另一个扇区。\n",
    "10^100 OmniNet": "10^100 全方位网络",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t\t": "\t\t\t",
    "\t\t": "\t\t",
    "\t": "\t",
    "\n": "\n",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\n\t": "\n\t",
    "\n\t": "\n\t",
    "\t\n": "\t\n",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) \$$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+)M minds$/, '$1M 思想'],
    [/^([\d\.,]+)k minds$/, '$1k 思想'],
    [/^([\d\.,]+)k votes$/, '$1k 投票'],
    [/^([\d\.,]+)B votes$/, '$1B 投票'],
    [/^([\d\.,]+)M votes$/, '$1M 投票'],
    [/^([\d\.,]+) votes$/, '$1 投票'],
    [/^([\d\.]+) media \$\/sec$/, '$1 媒体 \$\/秒'],
    [/^([\d\.,]+) media \$\/sec$/, '$1 媒体 \$\/秒'],
    [/^([\d\.,]+) politics \$\/sec$/, '$1 政治 \$\/秒'],
    [/^([\d\.,]+) votes\/sec$/, '$1 投票\/秒'],
    [/^([\d\.,]+) minds\/sec$/, '$1 思想\/秒'],
    [/^([\d\.,]+) industry \$\/sec$/, '$1 工业 \$\/秒'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);